---
# hostname: localhost
domain: local.domain
timezone: Europe/Berlin
dns1: 10.0.2.3
dns2: 10.0.2.4
securelevel: -1
securelevel_enable: NO

add_interfaces: lo1
ifconfig_lo1: 127.0.1.1/24

local_host_entry:
  - { name: "127.0.0.1", value: "localhost localhost.local {{ hostname }}" }

rcconf:
  - { name: "sshd_enable", value: "YES" }
  - { name: "syslog_enable", value: "NO" }
  - { name: "sendmail_enable", value: "NO" }
  - { name: "kern_securelevel", value: "{{ securelevel }}" }
  - { name: "kern_securelevel_enable", value: "{{ securelevel_enable }}" }
  - { name: "jail_parallel_start", value: "YES" }

rcconf_network:
  - { name: "ifconfig_DEFAULT", value: "SYNCDHCP" }
  - { name: "cloned_interfaces", value: "{{ add_interfaces }} " }
  - { name: "ifconfig_lo1", value: "{{ ifconfig_lo1 }}" }

# Default jail conf
rcconf_jail:
  - { name: "sendmail_enable", value: "NONE" }
  - { name: "syslog_enable", value: "-ss" }
  - { name: "rpcbind_enable", value: "NO" }

sysctl:
  - { name: "kern.securelevel", value: "{{ securelevel }}" }
  - { name: "security.bsd.see_other_uids", value: "0" }
  - { name: "security.bsd.see_other_gids", value: "0", unset: "yes" }

resolvconf:
  - { line: "search {{ domain }}" }
  - { line: "nameserver {{ dns1 }}" }
  - { line: "nameserver {{ dns2 }}" }
