---
- local_action: stat path=host_vars/{{ hostname }}.yml
  register: hostvar
  become: no

- include_vars: host_vars/{{ hostname }}.yml
  when: hostvar.stat.exists

- include: users.yml
- include: permissions.yml
- include: directories.yml
- include: config.yml
- include: control.yml
