---
- name: Set rcconf | FreeBSD
  template:
    src: roles/settings/templates/rc.conf.j2
    dest: /etc/rc.conf
    owner: root
    group: 0
    mode: 0644
  with_items: "{{ rcconf }}"
  tags:
    - set_rcconf
