---
- hosts: server
  user: vagrant
  become: yes
  become_method: sudo
  gather_facts: no 
  roles:
    - { role: bootstrap }
    - { role: users }
    - { role: settings }
    - { role: pf }
    - { role: jails }
